### ISSUE TITLE
Leaderboard + user ranking should not be part of MVP

### ISSUE THREAD

**Issue by brookeangel** [cssimms/tictactactics#1]
I'd put that as a bonus goal to make sure you have enough time to get your tic tac toe game nicely styled! I think you can reach it but better to feel awesome about completing a bonus than to feel stressed for time. 

On that note, give yourself an extra day for phase 2 - looks like you've got a lot of stuff packed in and it's better to be a bit ahead of schedule.

**Comment by cssimms** [comment]
Good plan, fixed!
