### ISSUE TITLE
Save game in flux-cycles.md

### ISSUE THREAD

**Issue by brookeangel** [cssimms/tictactactics#2]
Since you are playing correspondence tic tac toe with another player, you should technically be invoking saveGame/updateGame every time you make a move - it needs to save to the database to be sent to the other player

**Comment by cssimms** [comment]
Yes! ok so saveGame should be invoked from CurrentGame still, but on any handleSubmit (the event callback for the submit move button). right?

**Comment by brookeangel** [comment]
Yup!
