### ISSUE TITLE
Build in time for game validations

### ISSUE THREAD

**Issue by brookeangel** [cssimms/tictactactics#3]
Make sure you build in ample time to do validations from the backend - it seems like your project will require a lot of validating who has moved last, what moves are legal, etc.

**Comment by brookeangel** [comment]
You will also have to have game logic both front end and back end O_O front end so users can get immediate feedback, back end so that leet haxors dont submit illegal moves... make sure to account for this time

**Comment by cssimms** [comment]
O.o you're right. I was thinking all on the frontend and just throw results to the database, but I have to look out for those haxors.

**Comment by cssimms** [comment]
So I could write some custom validations in the game model with game logic... does that make any sense?

Related note, where exactly should the frontend game logic live? I'm having a hard time visualizing how I can run a game and have to communicate to my components. Where should that data flow to and from? I guess the game logic could talk to the actions?

**Comment by brookeangel** [comment]
Yup - totally just write some custom validations on the model level. The fact that the app is split between a rails backend and a js frontend makes the game logic a little trickier unfortunately, but we can make it happen! 

I would put the frontend game logic in a util file since it doesn't have much to do directly with the components. Tic tac toe squares can keep data (props or something of the sort) on where they live, then every time one is clicked and goes to an onClick handler, you can check with the frontEnd game logic that the move is legit before sending it to the backend. Custom validations would definitely work for the backend.

**Comment by cssimms** [comment]
added to the planning phases!
